name: build Arduino code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - uses: arduino/compile-sketches@v1
      with:
        fqbn: "arduino:avr:uno"
        libraries: |
          - name: Servo
          - name: Stepper
            version: 1.1.3
